version: 1.1.0

system-variables:
  - file-path: ..\..\FanControlECU\FanControl_Canoe\SysVar\VTT.vsysvar
  - file-path: ..\..\..\FanModel\TestInterface.vsysvar
  
datasources:
  input-files:
    - file-path: ..\..\FanControlECU\FanControl_VTT\SUT\FanControlECU.vCODM


application-models:
  - file-path: ..\..\..\FanModel\Fan.can
  - file-path: ..\..\FanControlECU\FanControl_VTT\SUT\FanControlECU.vModule
  - file-path: ..\..\FanControlECU\FanModel\SymbolMapping.can
