name: Test Workflow

on:
  push:
  workflow_dispatch:

jobs:

  canoe:
    runs-on: [Windows,canoe-arc]
    steps:
      - name: check Canoe version
        shell: powershell
        run: canoe4sw-se.exe --version
      - name: Sleep for 20 minutes using PowerShell
        run: Start-Sleep -Seconds 1200
        shell: powershell
