name: Test Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build-sut:
    runs-on: [Windows,vtt-arc]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: check Canoe version
        shell: powershell
        run: canoe4sw-se.exe --version
