name: Test Workflow

on:
  push:
  workflow_dispatch:

jobs:
  vtt:
    runs-on: [Windows,vtt-arc]
    steps:
      - name: check vtt help
        shell: powershell
        run: vttmake help
          
  testunitbuildcli:
    needs: vtt
    runs-on: [Windows,testunitbuildcli-arc]
    steps:
      - name: check testunitbuildcli version
        shell: powershell
        run: TestUnitBuildCLI.exe --version
        
  canoe:
    needs: testunitbuildcli
    runs-on: [Windows,canoe-arc]
    steps:
      - name: check Canoe version
        shell: powershell
        run: canoe4sw-se.exe --version
       
  testreportviewer:
    needs: canoe
    runs-on: [Windows,testreportviewer-arc]
    steps:
      - name: check testreportviewer help
        shell: powershell
        run: ReportViewerCli -h
